name: Trigger auto deployment for streamlit-ui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/streamlit-ui-AutoDeployTrigger-9bd28a4f-bf36-4443-996f-31894799f1df.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.STREAMLITUI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: sragregistry.azurecr.io
          registryUsername: ${{ secrets.STREAMLITUI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STREAMLITUI_REGISTRY_PASSWORD }}
          containerAppName: streamlit-ui
          resourceGroup: niti-rag_group
          imageToBuild: sragregistry.azurecr.io/streamlit-ui:${{ github.sha }}
          
            

     

